services:
  db:
    image: postgres:13
    container_name: postgres-corfo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbtest
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes: {}